### ISSUE TITLE
UnboundLocalError: local variable 'joined' referenced before assignment

### ISSUE THREAD

**Issue by palomo11** [ziyewang/COMEBin#1]
Hi, I'm trying to run COMEBin but I'm encountering the following issue:

```
Traceback (most recent call last):
  File "main.py", line 368, in <module>
    main()
  File "main.py", line 352, in main
    run_gen_cov(logger, args)
  File "/work/ese-alexp/software/python/anaconda3/2021.11/envs/comebin_v103/bin/COMEBin/data_aug/gen_cov.py", line 302, in run_gen_cov
    gen_cov_from_bedout(logger, args.out_augdata_path, out, num_aug=args.n_views-1, contig_len=args.contig_len,num_process=args.num_threads)
  File "/work/ese-alexp/software/python/anaconda3/2021.11/envs/comebin_v103/bin/COMEBin/data_aug/gen_cov.py", line 244, in gen_cov_from_bedout
    joined.to_csv(outfile, sep='\t', header=True)
UnboundLocalError: local variable 'joined' referenced before assignment
```

This is the command I'm running:

```
run_comebin.sh -a contigs_1000.fasta -o comebin_bins -p /data/sort_bam_files -t 40
```

This is the log file:

```
2023-11-01 15:02:38,764 - generate_aug_data: fastafile
2023-11-01 15:05:53,818 - aug:	1
2023-11-01 15:06:55,554 - aug:	2
2023-11-01 15:08:01,244 - aug:	3
2023-11-01 15:09:04,357 - aug:	4
2023-11-01 15:10:05,453 - aug:	5
2023-11-01 15:11:10,134 - Generate coverage files from bam files.
Traceback (most recent call last):
  File "main.py", line 368, in <module>
    main()
  File "main.py", line 352, in main
    run_gen_cov(logger, args)
  File "/work/ese-alexp/software/python/anaconda3/2021.11/envs/comebin_v103/bin/COMEBin/data_aug/gen_cov.py", line 302, in run_gen_cov
    gen_cov_from_bedout(logger, args.out_augdata_path, out, num_aug=args.n_views-1, contig_len=args.contig_len,num_process=args.num_threads)
  File "/work/ese-alexp/software/python/anaconda3/2021.11/envs/comebin_v103/bin/COMEBin/data_aug/gen_cov.py", line 244, in gen_cov_from_bedout
    joined.to_csv(outfile, sep='\t', header=True)
UnboundLocalError: local variable 'joined' referenced before assignment
```

**Comment by ziyewang** [comment]
Hi,

Thank you for choosing COMEBIn. This issue can likely be attributed to one of two causes:
1) There might not be any corresponding BAM files located in the specified path.
2) The BAM file may not encompass all the contigs found in the 'contigs_1000.fasta' file.
Please note that our code utilizes all BAM files with names ending in ".bam" within the 'sort_bam_files' directory. Ensure that there are no other files with similar naming patterns in that directory to avoid any conflicts.

Please let me know if there is still an issue. Thanks very much.

Best,
Ziye

**Comment by palomo11** [comment]
Hi, thanks for the suggestion. The issue was that my BAM files were not ending in ".bam" but in "bam.sort". I have changed that, and COMEbin has now properly run.
