### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by MjelleLab** [ziyewang/COMEBin#11]
Hi, any idea what this is? My data is single-read and things worked fine until this step. 

Running getting representation.
2024-03-01 20:41:57,205 - train
2024-03-01 20:41:57,231 - Generate features for the data.
Traceback (most recent call last):
  File "/mnt/scratch/robinm/software/COMEBin/COMEBin/main.py", line 369, in <module>
    main()
  File "/mnt/scratch/robinm/software/COMEBin/COMEBin/main.py", line 289, in main
    train_CLmodel(logger,args)
  File "/mnt/scratch/robinm/software/COMEBin/COMEBin/train_CLmodel.py", line 38, in train_CLmodel
    dataset, namelist = get_ContrastiveLearningDataset(args.data, args.n_views,
  File "/mnt/scratch/robinm/software/COMEBin/COMEBin/get_augfeature.py", line 155, in get_ContrastiveLearningDataset
    dataset, namelist = get_kmer_coverage(data_path, n_views, kmer_model_path, device, nokmer, cov_meannormalize, cov_minmaxnormalize, cov_standardization,addvars,vars_sqrt,kmer_l2_normalize,kmerMetric_notl2normalize)
  File "/mnt/scratch/robinm/software/COMEBin/COMEBin/get_augfeature.py", line 41, in get_kmer_coverage
    covIdxArr = np.empty(len(mapObj), dtype=np.int)
  File "/mnt/scratch/robinm/software/mambaforge/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?
Something went wrong with running training network. Exiting.

**Comment by ziyewang** [comment]
Hi,

It could be an issue with the numpy version. Would you like to uninstall the current numpy version from the environment and try installing version 1.19.0?

https://github.com/ziyewang/COMEBin/blob/master/comebin_env.yaml

Best,
Ziye

**Comment by MjelleLab** [comment]
Problem solved using the Conda installation instead. Sorry for the inconvenience!
