### ISSUE TITLE
Error in get_final_results.py : ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by r-frizzo** [ziyewang/COMEBin#17]
Hi! Sorry to bug you again.
I've tested COMEBin with the test data provided and a reduced dataset and everything ran fine.
Now I'm trying to bin contigs generated by the co-assembly of five samples, but I'm consistently getting this error after the `Run unitem profile` step:
```
Traceback (most recent call last):
  File "main.py", line 369, in <module>
    main()
  File "main.py", line 365, in main
    run_get_final_result(logger, args, seed_num, num_threads, ignore_kmeans_res=True)
  File "/stor/progetti/p1037/p1037u03/miniconda3/envs/comebin/bin/COMEBin/get_final_result.py", line 232, in run_get_final_result
    best_method = estimate_bins_quality_nobins(bac_mg_table, ar_mg_table, args.output_path + '/cluster_res/',ignore_kmeans_res=ignore_kmeans_res)
  File "/stor/progetti/p1037/p1037u03/miniconda3/envs/comebin/bin/COMEBin/get_final_result.py", line 190, in estimate_bins_quality_nobins
    bin_quality_dict, best_method = get_bin_quality(orig_bins, methods_sorted, markers)
  File "/stor/progetti/p1037/p1037u03/miniconda3/envs/comebin/bin/COMEBin/get_final_result.py", line 90, in get_bin_quality
    sum_max = max(sum_list)
ValueError: max() arg is an empty sequence
```
Any idea on what might be causing it?

Thank you! 
Riccardo

Here's the full log:
[comebin_error_15Mar24.txt](https://github.com/ziyewang/COMEBin/files/14618420/comebin_error_15Mar24.txt)

**Comment by ziyewang** [comment]
Hi，

Could you please provide the number of contigs? Also, do you have any results starting with 'Leiden' in the directory /stor/progetti/p1037/p1037u03/data/boschettona23/coassembly_07feb24/art/comebin/comebin_res/cluster_res? If not, it might indicate that the Leiden clustering method was not successfully called in parallel. 

Best,
Ziye

**Comment by r-frizzo** [comment]
Hello Ziye, here are the contigs statistics:
```
Number of contigs	2655613
Total length	5587909979
Longest contig	263117
Shortest contig	1000
N50	2166
N90	1125
```
The cluster_res folder contains: 
- unitem_profile
- weight_seed_kmeans_k_1054_result.tsv_bins
- weight_seed_kmeans_k_1054_result.tsv

no results starting with `Leiden`.

I've run this instance on a HPC with 20 CPUs, 600G of RAM and GPU.

Riccardo

**Comment by ziyewang** [comment]
Hi,
It seems that the memory was insufficient when running Leiden in parallel due to the large number of sequences exceeding 2,000,000. Could you please try reducing the num_threads parameter in the original command to see if it resolves the issue while retaining the current results? This way, we can skip data augmentation and training steps. If it still doesn't run successfully, I can test it with a similarly large dataset in a couple of days to address this problem.

Best,
Ziye

**Comment by r-frizzo** [comment]
Ok! I'll restart the run with 2 CPUs.

Here's also the HPC job report:
````
CPU Utilized: 04:04:24
CPU Efficiency: 17.37% of 23:26:45 core-walltime
Job Wall-clock time: 01:33:47
Memory Utilized: 221.44 GB
Memory Efficiency: 36.91% of 600.00 GB
````

Thank you, I'll let you know when I have news!
Riccardo

**Comment by r-frizzo** [comment]
Done! 
Unfortunately, I've got the same error, and still no Leiden files in the 'cluster_res' folder.

Here's the HPC job report for the 2 CPU run:
```
CPU Utilized: 04:18:01
CPU Efficiency: 80.77% of 05:19:26 core-walltime
Job Wall-clock time: 02:39:43
Memory Utilized: 26.25 GB
Memory Efficiency: 4.38% of 600.00 GB
```
Way less memory usage with 2 CPUs! 
Are the Leiden files generated by the cluster.py script? I'd like to try and pinpoint the problem

**Comment by ziyewang** [comment]
Hi,

The Leiden files are generated by the cluster.py script (Line 381-418).

Best,
Ziye

**Comment by PonderLi** [comment]
Hello, I encountered the same error message. Did you manage to resolve this issue? I would greatly appreciate it if you could provide some solutions.

**Comment by XC-Zhai** [comment]
I also have the same error with 1 TB memory that was required from the HPC machine. I have 987401 sequences for inputs. Much appreciated for the potential solutions. Best, Xichuan

**Comment by kassipan** [comment]
Hi, 
Thank you for providing this great tool to the community!

I'd like to report that I also face the same issues when it comes to the clustering phase.
Reducing my assembly down to 942810 contigs but also experimenting with number of threads and available memory has not helped. 
Even when utilising an 8TB node on HPC cluster the clustering method seems to not be working properly.

I'd greatly appreciate any suggestions.

Best,
Kassi

**Comment by sergeibukin** [comment]
> Hi, Thank you for providing this great tool to the community!
> 
> I'd like to report that I also face the same issues when it comes to the clustering phase. Reducing my assembly down to 942810 contigs but also experimenting with number of threads and available memory has not helped. Even when utilising an 8TB node on HPC cluster the clustering method seems to not be working properly.
> 
> I'd greatly appreciate any suggestions.
> 
> Best, Kassi

Reducing the value of the "max_eages_list" parameter in the cluster.py script (line 380) sometimes solves this problem. Just try to change "max_eages_list = 100" to "max_eages_list = 50"

**Comment by yqy6611** [comment]
Seems like COMEbin cannot allocate memory well. Another option is using contigs longer than 1500 bps or 2000 bps if necessary to eliminate short ones.

**Comment by ziyewang** [comment]
Thanks for reporting this. The error occurs because Leiden did not produce valid clustering results, likely due to the high memory requirements of clustering a very large assembly. COMEBin v1.1.0 reduces Leiden’s memory usage and now reports a more specific error when clustering fails.

Best,
Ziye
