### ISSUE TITLE
logits error

### ISSUE THREAD

**Issue by jasonsahl** [ziyewang/COMEBin#23]
Hello,

I'm getting an error that was seen in a closed thread, but the fixes did not address my problem. I'm running v1.0.4 on an assembly that has >56,000 contigs. I've tried using a BAM file created through the "gen_cov_file.sh" script. The error is:

Traceback (most recent call last):
  File "main.py", line 369, in <module>
    main()
  File "main.py", line 289, in main
    train_CLmodel(logger,args)
  File "/projects/comp_genomics/sahl/tools/miniconda/envs/comebin_env/bin/COMEBin/train_CLmodel.py", line 236, in train_CLmodel
    simclr.train_addpretrain(train_loader, dataset, namelist)
  File "/projects/comp_genomics/sahl/tools/miniconda/envs/comebin_env/bin/COMEBin/simclr.py", line 300, in train_addpretrain
    top1, top5 = accuracy(logits, labels, topk=(1, 5))
UnboundLocalError: local variable 'logits' referenced before assignment
Something went wrong with running training network. Exiting.

I have successfully run the pipeline on the sample data. Any help would be appreciated.

thanks

**Comment by ziyewang** [comment]
Thanks for reporting this. The error occurred when the number of trainable contigs remaining after length filtering was smaller than the requested batch size, causing the DataLoader to produce no batches. COMEBin v1.1.0 automatically adjusts the batch size and validates the training dataset before starting. This issue has been addressed in v1.1.0.
