### ISSUE TITLE
Error when generating coverage files from bam files

### ISSUE THREAD

**Issue by eperezv** [ziyewang/COMEBin#27]
Hi,

I'm having the following issue. Any idea on what is wrong or how to solve?
Thank you

```
(comebin_env) eduardo@eduardo-PC:~/tools/COMEBin/COMEBin$ ./run_comebin.sh -a /mnt/COAL/concatenated/concatenated.fa -o comebin -p /mnt/COAL/concatenated/*.sorted.bam -t 12
Batch size: 1024
N50: 7627
Tau(temperature): 0.15
/home/eduardo/tools/COMEBin/COMEBin/comebin/data_augmentation does not exist.
Running data augmentation.
2024-09-05 13:43:27,122 - generate_aug_data: fastafile
2024-09-05 13:49:56,563 - aug:  1
2024-09-05 13:53:24,114 - aug:  2
2024-09-05 13:56:50,180 - aug:  3
2024-09-05 14:00:15,815 - aug:  4
2024-09-05 14:03:41,072 - aug:  5
2024-09-05 14:07:06,761 - Generate coverage files from bam files.
Traceback (most recent call last):
  File "main.py", line 369, in <module>
    main()
  File "main.py", line 353, in main
    run_gen_cov(logger, args)
  File "/home/eduardo/tools/COMEBin/COMEBin/data_aug/gen_cov.py", line 301, in run_gen_cov
    run_gen_bedtools_out(bam_file_path, out, logger,num_process=args.num_threads)
  File "/home/eduardo/tools/COMEBin/COMEBin/data_aug/gen_cov.py", line 76, in run_gen_bedtools_out
    filenames = os.listdir(bam_file_path)
NotADirectoryError: [Errno 20] Not a directory: '/mnt/COAL/concatenated/GT14BAa.sorted.bam/'
Something went wrong with running generating augmentation data. Exiting.
```

**Comment by ziyewang** [comment]
Hi,

"-p" input refers to the path where the BAM files to be processed are stored (the program will identify all files with the .bam extension in the specified directory). If there are other files ending with .bam in the directory, please create a new folder to store only the BAM files that need to be processed.

Best,
Ziye

**Comment by eperezv** [comment]
I see. Thanks for clarifying.
